= Docker container for gitlab-runner-gradle
v0.1, {localdate}
:author: Alexey Ukhov, startext GmbH
:email: <mail@startext.de>
:icons: font
:numbered:
:toc:
:toclevels: 3
:encoding: utf-8
:source-highlighter: coderay


== Introduction

This container is based on official docker container from gitlab.
We just add necessary software for our projects building (java, gradle, git, etc).

Detailed description of official docker container installation is here: +
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/install/docker.md

== Installation

[[build_docker_image]]
=== Build docker image

[source,bash]
----
$ sudo ./build_image.sh
Successfully built 2a2677eb307d
----

Result: image with name `startext/gitlab-runner-gradle` registered in local repository:

[source,bash]
----
$ docker images startext/gitlab-runner-gradle
REPOSITORY                      TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
startext/gitlab-runner-gradle   latest              2a2677eb307d        44 seconds ago      1.117 GB
----

[[create_docker_container]]
=== Docker container creation

Create two containers (config and runner):

[source,bash]
----
$ docker run -d --name gitlab-runner-config \
    -v /etc/gitlab-runner \
    busybox:latest \
    /bin/true

$ docker run -d --name gitlab-runner-gradle --restart always \
    --volumes-from gitlab-runner-config \
    startext/gitlab-runner-gradle:latest
----

=== Register the runner

[source,bash]
----
$ docker exec -it gitlab-runner-gradle gitlab-runner register \
  --non-interactive \
  --url "https://startext.tomsk.ru:5000/ci" \
  --registration-token "TOKEN_HERE" \
  --name "runner-name" \
  --executor "shell" \
  --tag-list "java,gradle,nodejs"
INFO[0000] TN4Lx9Wp Registering runner... succeeded
INFO[0000] Runner registered successfully. Feel free to start it, but if it's running already the config should be automatically reloaded!
----

== Update

* Pull the latest version:
[source,bash]
----
docker pull startext/gitlab-runner-gradle:latest
----
or rebuild docker image. See <<build_docker_image>> section.

* Stop and remove the existing container:
[source,bash]
----
$ docker stop gitlab-runner-gradle && docker rm gitlab-runner-gradle
----
* Create docker container with runner as it's described in section <<create_docker_container>>.
[source,bash]
----
$ docker run -d --name gitlab-runner-gradle --restart always \
    --volumes-from gitlab-runner-config \
    startext/gitlab-runner-gradle:latest
----

== Manual build from gitlab-runner original image

=== Create docker containers

[source, bash]
----
docker run -d --name gitlab-runner-config \
    -v /etc/gitlab-runner \
    busybox:latest \
    /bin/true

docker run -d --name gitlab-runner --restart always \
    --volumes-from gitlab-runner-config \
    startext/gitlab-runner:latest
----

=== Register the runner

[source, bash]
----
docker exec -it gitlab-runner gitlab-runner register \
  --non-interactive \
  --url "https://startext.tomsk.ru:5000/ci" \
  --registration-token "REGISTRATION_TOKEN" \
  --description "gitlab-runner-name" \
  --executor "shell" \
  --tag-list "java,gradle,nodejs"
----

=== Software installation

==== System packages installation

[source,bash]
----
sudo apt-get update
sudo apt-get install -y software-properties-common git libfontconfig1 libc6-dev
----

==== Oracle JDK installation

[source,bash]
----
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update
sudo apt-get install oracle-java8-installer
----

==== Gradle installation
[source,bash]
----
sudo add-apt-repository ppa:cwchien/gradle -y
sudo apt-get update
sudo apt-get install -y gradle-ppa
----

==== NodeJS installation

[source,bash]
----
sudo curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g npm
----
